#+title: TODO Datamining
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: p:t
** DATA MINING

2022-2023

Titular curs: Prof. dr. Anca ANDREICA (anca.andreica at ubbcluj.ro)

Specializarile de Masterat:
Anul 1 Baze de date
Anul 1 Sisteme distribuite in Internet

Nota finala se va calcula tinand cont de:
- proiect (50%)
- prezentare eseu (50%)


Proiect:
- realizat in echipe de 3-5 studenti
- tema poate fi aleasa de catre echipa din domeniul studiat la curs
- idei teme posibile
- proiectul se prezinta la seminar, inainte de finalizarea semestrului
- in lipsa prezentarii nota acordata este 1


Eseu:
- prezentat in fata colegilor in aprox 6 minute
- tema trebuie aleasa de catre student din domeniul studiat la curs
- studentii trebuie sa se planifice pana cel tarziu in 27 noiembrie 2022 pentru prezentarea acestuia intr-una din zilele: 6 decembrie 2022, 13 decembrie 2022, 20 decembrie 2022, 10 ianuarie 2023 sau 17 ianuarie 2023; pentru planificare va rog sa trimiteti un mail la adresa anca.andreica at ubbcluj.ro (planificarea se va face in limita locurilor disponibile si poate fi vizualizata aici).
- studentii pot face prezentari si pe parcursul semestrului, incepand cu saptamana 4; in acest scop, studentii trebuie sa se planifice pentru prezentare cu cel putin o saptamana inainte
- in lipsa prezentarii nota acordata este 1


In sesiunea de examene si sesiunea de restante nota se va calcula astfel:
- nota de la proiect din timpul semestrului (50%) - nu se pot preda proiecte decat inainte de sesiune
- prezentare eseu (50%) - cu planificare prealabila prin email (verificati aici planificarea)


* TODO Referat
DEADLINE: <2022-12-13 Tue>
- Individual

* TODO Proiect
** TODO presentation
a. Use Chebyshev distance
b. Move clustering first 5 moves
c. get first 5 moves:
   + openings based on rating

d. k-means: classification
e. clustering?
f. 3 informatii
   1. rating
   2. miscare
   3. frecventa
g. tabel clustering (k-means)
   - (x.rating - y.rating) + (x.miscare - y.miscare)
   - E4 -> E5 -> 1 mutare
   - QE4 ->
** TODO Data usage project (seperate one)
